#!/bin/sh
set -x

#time
deps+=(ntp) # do not use on a laptop -- chronis

#shell
deps+=(bash-completion zsh zsh-completions)
deps+=(sudo git openssh mosh gnupg)
deps+=(tmux ranger stow htop tree)
deps+=(nmap nbtscan bind-tools rfkill)
deps+=(perl-rename unzip)

#vim
deps+=(gvim neovim python2 python)

#aur
aurdeps+=(powerpill bauerbill)


pacman -S --needed "${deps[@]}"

#TODO install cower
#TODO install pacaur

pacaur -Ss "${aurdeps[@]}"

systemctl start ntpd
systemctl enable ntpd


