#!/bin/sh
set -x

#shell
deps+=(bash-completion)
deps+=(sudo git openssh mosh gnupg)
deps+=(tmux ranger stow htop tree)
deps+=(nmap nbtscan bind-tools rfkill)
deps+=(perl-rename unzip)

#vim
deps+=(gvim neovim python2 python)

pacman -S --needed "${deps[@]}"

# yay - aur helper in golang
mkdir -p ~/Projects
cd ~/Projects
git clone https://aur.archlinux.org/yay
cd yay
makepackage -si

