#!/usr/bin/python3

import os, sys

if os.geteuid() != 0:
    exit(3)

rule = """
/* Allow users in wheel group to use blueman feature requiring root without authentication */
polkit.addRule(function(action, subject) {
    if ((action.id == "org.blueman.network.setup" ||
         action.id == "org.blueman.dhcp.client" ||
         action.id == "org.blueman.rfkill.setstate" ||
         action.id == "org.blueman.pppd.pppconnect") &&
        subject.isInGroup("wheel")) {
        return polkit.Result.YES;
    }
});
"""

if not os.path.exists('/etc/polkit-1/rules.d'):
    os.makeidrs('/etc/polkit-1/rules.d')

with open('/etc/polkit-1/rules.d/blueman.conf', 'w') as f:
    f.write(rule)
