---
- name: sshd_config
  block:
    - lineinfile: path=/etc/ssh/sshd_config backrefs=yes
                  regexp="^\s*({{ item }})" line="\1 no"
      with_items:
        - PermitRootLogin
        - PermitEmptyPasswords

    - name: ipv4 only
      lineinfile: path=/etc/ssh/sshd_config backrefs=yes
                  regexp="^[\s#]*(AddressFamily)" line="\1 inet4"

    - name: no ipv6 listen
      lineinfile: path=/etc/ssh/sshd_config
                  regexp="^[\s#]*ListenAddress ::" state=absent

    - name: LogLevel to show key fingerprints
      lineinfile: path=/etc/ssh/sshd_config backrefs=yes
                  regexp="^\s*(LogLevel)" line="\1 VERBOSE"

    - name: LoginGraceTime
      lineinfile: path=/etc/ssh/sshd_config backrefs=yes
                  regexp="^[\s#]*(LoginGraceTime)" line="\1 15"

    - name: MaxAuthTries
      lineinfile: path=/etc/ssh/sshd_config backrefs=yes
                  regexp="^[\s#]*(MaxAuthTries)" line="\1 3"

    - name: PubkeyAuthentication
      lineinfile: path=/etc/ssh/sshd_config backrefs=yes
                  regexp="^[\s#]*(PubkeyAuthentication)" line="\1 yes"

    - name: AllowUsers
      lineinfile: path=/etc/ssh/sshd_config backrefs=yes
                  regexp="^[\s#]*(AllowUsers)" line="{{ users.admin }}@127.0.0.1"

    - name: AllowUsers
      lineinfile: path=/etc/ssh/sshd_config backrefs=yes
                  regexp="^[\s#]*(AllowUsers)" line="{{ users.user }}@127.0.0.1"

- name: iptables base setup
  shell: |
    # FLUSH EVERYTHING
    iptables  -F
    ip6tables -F

    iptables  -X
    ip6tables -X

    iptables  -Z
    ip6tables -Z

    # TCP SYN FLOOD: DoS
    iptables  -A INPUT -p tcp ! --syn -m state --state NEW -j DROP
    ip6tables -A INPUT -p tcp ! --syn -m state --state NEW -j DROP

    # TCP NULL: portscan
    iptables  -A INPUT -p tcp --tcp-flags ALL NONE -j DROP
    ip6tables -A INPUT -p tcp --tcp-flags ALL NONE -j DROP

    # TCP XMAS: portscan
    iptables  -A INPUT -p tcp --tcp-flags ALL ALL -j DROP
    ip6tables -A INPUT -p tcp --tcp-flags ALL ALL -j DROP

    # SSH
    iptables  -A INPUT -p tcp -m tcp --dport 22 -j ACCEPT
    ip6tables -A INPUT -p tcp -m tcp --dport 22 -j ACCEPT

    iptables  -I INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT
    ip6tables -I INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT

    iptables  -A INPUT -i lo -j ACCEPT
    ip6tables -A INPUT -i lo -j ACCEPT

    # POLICY
    iptables  -P OUTPUT ACCEPT
    ip6tables -P OUTPUT ACCEPT

    iptables  -P INPUT DROP
    ip6tables -P INPUT DROP

    iptables  -P FORWARD DROP
    ip6tables -P FORWARD DROP

    iptables-save  >| /etc/iptables/save.v4
    ip6tables-save >| /etc/iptables/save.v6
  become: true
...
